name: blogwebsite

highlighter: pygments
markdown: kramdown
kramdown:
  input:           GFM
  auto_ids:        true
  auto_id_prefix:  'id-'

permalink: /blog/:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
