name: blogwebsite

highlighter: rouge
markdown: kramdown
kramdown:
  input:           GFM
  auto_ids:        true
  auto_id_prefix:  'id-'
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


permalink: /blog/:year/:month/:day/:title

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

url: "https://xxleyigithub.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
