name: blogwebsite

highlighter: pygments
markdown: kramdown
kramdown:
  input:           GFM
  auto_ids:        true
  auto_id_prefix:  'id-'
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


permalink: /blog/:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
